// Generated by scripts/generate-asset-manifest.mjs from actual application imports.
import { ArrowClockwise, ArrowsLeftRight, BookOpenText, CaretDown, Check, DownloadSimple, ImagesSquare, LockSimple, MagnifyingGlass, PictureInPicture, PlayCircle, SquaresFour, Sticker, X } from '@phosphor-icons/react';
export const usedIcons = { ArrowClockwise, ArrowsLeftRight, BookOpenText, CaretDown, Check, DownloadSimple, ImagesSquare, LockSimple, MagnifyingGlass, PictureInPicture, PlayCircle, SquaresFour, Sticker, X };
