// Generated by scripts/generate-asset-manifest.mjs from actual application imports.
import { ArrowClockwise, ArrowsLeftRight, CaretDown, ChatCircleText, Check, DownloadSimple, ImagesSquare, LockSimple, MagnifyingGlass, PaperPlaneRight, PictureInPicture, PlayCircle, Sparkle, X } from '@phosphor-icons/react';
export const usedIcons = { ArrowClockwise, ArrowsLeftRight, CaretDown, ChatCircleText, Check, DownloadSimple, ImagesSquare, LockSimple, MagnifyingGlass, PaperPlaneRight, PictureInPicture, PlayCircle, Sparkle, X };
