// Generated by scripts/generate-asset-manifest.mjs from actual application imports.
import { ArrowRight, ArrowSeparate, Check, Download, Lock, MediaImageList, MultiWindow, MusicNote, NavArrowDown, NavArrowLeft, OpenBook, PauseSolid, PlaySolid, Refresh, Search, SoundHigh, SoundOff, Sparks, ViewGrid, Xmark } from 'iconoir-react';
export const usedIcons = { ArrowRight, ArrowSeparate, Check, Download, Lock, MediaImageList, MultiWindow, MusicNote, NavArrowDown, NavArrowLeft, OpenBook, PauseSolid, PlaySolid, Refresh, Search, SoundHigh, SoundOff, Sparks, ViewGrid, Xmark };
