import {useEffect,useRef,useState} from 'react';
import {Xmark,SoundHigh,Check} from 'iconoir-react';
import FoodModel from '../../assets-gallery/FoodModel.jsx';
import {getMouthTarget,isNearMouth,clamp} from '../../gameplay/gameplay-state.js';
import {FOOD_WORDS,WORD_COLORS,QUANTITY_WORDS,phraseParts,foodPhrase,AUTO_FEED_MS,BubblePractice,bubblePosition} from './words.js';
import './word-bubbles.css';
export default function WordBubbles({session,transcript,characterRect,onTarget,onGuide,onProgress,onFinish}){
 const host=useRef(null),practice=useRef(null);if(!practice.current)practice.current=new BubblePractice();
 const callbacks=useRef({onTarget,onGuide,onProgress,onFinish});callbacks.current={onTarget,onGuide,onProgress,onFinish};
 const bubblesRef=useRef([]),drag=useRef(null),flight=useRef(null),timers=useRef(new Set()),alive=useRef(false),done=useRef(false),seen=useRef(''),geometry=useRef({stage:{width:1,height:1},mouth:null,blocked:null}),pausedAt=useRef(0);
 const [bubbles,setBubbles]=useState([]),[index,setIndex]=useState(0),[stage,setStage]=useState({width:1,height:1}),[message,setMessage]=useState('念出一个词，把它变成泡泡');
 const [prompt,setPrompt]=useState(practice.current.prompt),[picker,setPicker]=useState(null);
 geometry.current={stage,mouth:getMouthTarget(characterRect,stage),blocked:characterRect};
 const commit=list=>{bubblesRef.current=list;setBubbles(list);};
 const delay=(fn,ms)=>{const id=setTimeout(()=>{timers.current.delete(id);if(alive.current&&!done.current)fn();},ms);timers.current.add(id);};
 function finish(){if(done.current)return;done.current=true;timers.current.forEach(clearTimeout);callbacks.current.onTarget?.(null);callbacks.current.onFinish?.({id:session.id,activityId:'words',createdAt:session.createdAt,report:practice.current.report()});}
 function feed(id){
  if(flight.current||drag.current||done.current)return;const bubble=bubblesRef.current.find(b=>b.id===id),mouth=geometry.current.mouth;if(!bubble||!mouth)return;
  flight.current=id;callbacks.current.onTarget?.({...mouth,mouthOpen:true,chewing:false});commit(bubblesRef.current.map(b=>b.id===id?{...b,phase:'flying',x:mouth.x,y:mouth.y}:b));setMessage('啊呜，泡泡飞到多米嘴边了');
  delay(()=>{commit(bubblesRef.current.map(b=>b.id===id?{...b,phase:'eating'}:b));const duration=callbacks.current.onTarget?.({...geometry.current.mouth,mouthOpen:false,chewing:true});delay(()=>{callbacks.current.onTarget?.(null);flight.current=null;practice.current.fed(bubble);callbacks.current.onProgress?.(practice.current.report());commit(bubblesRef.current.filter(b=>b.id!==id));setIndex(practice.current.index);setPrompt(practice.current.prompt);setPicker(null);setMessage(practice.current.index===10?'十个词都尝过啦！':'多米吃到了你的单词，再说一个吧');},Math.max(1300,Math.min(6000,Number(duration)||1800)));},matchMedia('(prefers-reduced-motion: reduce)').matches?100:650);
 }
 const feedRef=useRef(feed);feedRef.current=feed;
 useEffect(()=>{alive.current=true;const measure=()=>setStage({width:host.current.clientWidth,height:host.current.clientHeight});measure();const observer=new ResizeObserver(measure);observer.observe(host.current);const tick=setInterval(()=>{if(document.hidden||flight.current||drag.current)return;const next=bubblesRef.current.find(b=>b.phase==='floating'&&Date.now()-b.born>=AUTO_FEED_MS);if(next)feedRef.current(next.id);},250);const visibility=()=>{if(document.hidden)pausedAt.current=Date.now();else if(pausedAt.current){const elapsed=Date.now()-pausedAt.current;commit(bubblesRef.current.map(b=>({...b,born:b.born+elapsed})));pausedAt.current=0;}};const key=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();finish();}};window.addEventListener('keydown',key);document.addEventListener('visibilitychange',visibility);return()=>{alive.current=false;observer.disconnect();clearInterval(tick);timers.current.forEach(clearTimeout);callbacks.current.onTarget?.(null);window.removeEventListener('keydown',key);document.removeEventListener('visibilitychange',visibility);};},[]);
 useEffect(()=>{if(index<10)callbacks.current.onGuide?.(`Can you say ${foodPhrase(prompt)}? Then feed the bubble to me!`);else callbacks.current.onGuide?.('Well done! Ten yummy words. Thank you for sharing!');},[index,prompt.word,prompt.count,prompt.color]);
 useEffect(()=>{if(!transcript?.id||seen.current===transcript.id||done.current)return;seen.current=transcript.id;const heard=practice.current.hear(transcript.text);callbacks.current.onProgress?.(practice.current.report());if(!heard.length){setMessage('再试一次，用英语念水果或食物，也可以加上 one 到 five 和颜色');return;}let list=[...bubblesRef.current];for(const entry of heard){const existing=list.find(b=>b.word===entry.word&&b.phase==='floating');if(existing){list=list.map(b=>b.id===existing.id?{...b,...entry,born:Date.now()}:b);continue;}if(list.length>=3)continue;const point=bubblePosition(geometry.current.stage,geometry.current.blocked,list);list.push({...entry,...point,id:crypto.randomUUID(),born:Date.now(),phase:'floating'});}commit(list);setMessage('拖到多米嘴边，或者点一下泡泡喂给它');},[transcript?.id]);
 function choose(slot,value){if(practice.current.setPrompt({[slot]:value})){setPrompt({...practice.current.prompt});callbacks.current.onProgress?.(practice.current.report());}setPicker(null);}
 const choices=picker==='count'?QUANTITY_WORDS.map((text,i)=>({text,value:i+1})):picker==='color'?Object.entries(WORD_COLORS).map(([text,color])=>({text,value:text,color:color.hex})):picker==='word'?Object.keys(FOOD_WORDS).map(value=>({value,text:phraseParts({...prompt,word:value}).at(-1).text})):[];
 function point(e){const bounds=host.current.getBoundingClientRect();return {x:clamp(e.clientX-bounds.left,55,stage.width-55),y:clamp(e.clientY-bounds.top,80,stage.height-110)};}
 function start(e,b){if(flight.current||b.phase!=='floating')return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);drag.current={id:b.id,pointerId:e.pointerId,start:point(e),last:point(e),moved:false,element:e.currentTarget};commit(bubblesRef.current.map(item=>item.id===b.id?{...item,phase:'dragging'}:item));}
 function move(e){const d=drag.current;if(!d||d.pointerId!==e.pointerId)return;e.preventDefault();const p=point(e);d.last=p;d.moved ||=Math.hypot(p.x-d.start.x,p.y-d.start.y)>8;commit(bubblesRef.current.map(b=>b.id===d.id?{...b,...p}:b));callbacks.current.onTarget?.({...p,mouthOpen:isNearMouth(p,geometry.current.mouth,20),chewing:false});}
 function release(e,cancel=false){const d=drag.current;if(!d||d.pointerId!==e.pointerId)return;drag.current=null;try{d.element.releasePointerCapture(e.pointerId)}catch{}commit(bubblesRef.current.map(b=>b.id===d.id?{...b,phase:'floating',born:Date.now()}:b));if(!cancel&&(!d.moved||isNearMouth(d.last,geometry.current.mouth,20)))feed(d.id);else callbacks.current.onTarget?.(null);}
 return <section className="word-bubble-play" ref={host} role="region" aria-label="多米的单词泡泡" data-mouth-x={geometry.current.mouth?.x} data-mouth-y={geometry.current.mouth?.y} data-word-lesson={Math.min(index+1,10)} data-bubble-count={bubbles.length}>
 <header className="word-bubble-heading">
  <div className="word-bubble-toolbar"><button aria-label="结束单词泡泡" onClick={finish}><Xmark/></button><small>和多米念单词 · {Math.min(index+1,10)} / 10</small>{index===10?<button aria-label="把记录收进相册" onClick={finish}><Check/></button>:<button aria-label="再听一遍题干" onClick={()=>callbacks.current.onGuide?.(`Can you say ${foodPhrase(prompt)}?`)}><SoundHigh/></button>}</div>
  {index===10?<strong className="word-bubble-complete">单词泡泡完成啦</strong>:<>
   <div className="word-bubble-prompt" aria-label={`题干：${foodPhrase(prompt)}`} lang="en">{phraseParts(prompt).map((part,i)=>part.slot?<button key={part.slot} className={`word-prompt-token token-${part.slot}`} style={part.slot==='color'?{'--token-color':WORD_COLORS[prompt.color].hex}:undefined} aria-label={part.label} aria-expanded={picker===part.slot} aria-controls="word-bubble-suggestions" onClick={()=>setPicker(picker===part.slot?null:part.slot)}>{part.text}</button>:<span className="word-prompt-connector" key={i}>{part.text}</span>)}</div>
   <span className="word-bubble-meaning">{prompt.count?`${prompt.count}${({juice:'杯',milk:'杯',noodles:'碗',bread:'片',cake:'块',candy:'颗'})[prompt.word]||'个'}`:''}{WORD_COLORS[prompt.color]?.label||''}{FOOD_WORDS[prompt.word]?.label}</span>
   {picker&&<div id="word-bubble-suggestions" className="word-bubble-suggestions" role="group" aria-label={`选择${picker==='count'?'数量':picker==='color'?'颜色':'食物'}`}>{choices.map(choice=><button key={choice.value} aria-pressed={prompt[picker]===choice.value} style={choice.color?{'--choice-color':choice.color}:undefined} onClick={()=>choose(picker,choice.value)}>{choice.color&&<i aria-hidden="true"/>}{choice.text}</button>)}</div>}
  </>}
 </header>
 {bubbles.map(b=><button className={`word-food-bubble is-${b.phase}`} key={b.id} data-word={b.word} data-count={b.count} data-color={b.color||''} style={{left:b.x,top:b.y}} aria-label={`拖动${b.phrase}喂多米，也可以点一下或按回车喂食`} disabled={['flying','eating'].includes(b.phase)} onPointerDown={e=>start(e,b)} onPointerMove={move} onPointerUp={e=>release(e)} onPointerCancel={e=>release(e,true)} onLostPointerCapture={e=>release(e,true)} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();feed(b.id);}}}><span className="word-food-bubble-float"><FoodModel foodId={FOOD_WORDS[b.word].model} count={b.count} color={WORD_COLORS[b.color]?.hex} transparent autoRotate={b.phase==='floating'}/><b>{b.phrase}</b></span></button>)}
 <span className="sr-only" aria-live="polite">{message}</span>
 </section>;
}
